export const faqData = [
  {
    title: 'Apa itu aplikasi CoopChick ?',
    description:
      '<p><b>CoopChick</b> adalah sebuah aplikasi koperasi digital domain peternakan ayam yang dibuat untuk mempermudah para peternak ayam mengerjakan bisnisnya di zaman digital ini.</p><br><p>Berikut adalah logo dari CoopChick :</p><img srcset="../../static/faq-images/CoopChickLogo.jpg" alt="CoopChick Logo" width="400" >'
  },
  {
    title: 'Bagaimana cara melakukan pembayaran checkout e-commerce ?',
    description:
      '<p>Untuk melakukan <b>Checkout</b>, anda perlu dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pretium lectus quam id leo in vitae. Sit amet luctus venenatis lectus magna fringilla urna. Nisi est sit amet facilisis magna. Convallis a cras semper auctor neque vitae tempus quam pellentesque. In arcu cursus euismod quis viverra nibh cras pulvinar mattis. Consectetur adipiscing elit ut aliquam. Nisl condimentum id venenatis a condimentum vitae sapien pellentesque habitant. Adipiscing elit duis tristique sollicitudin nibh sit amet commodo nulla. Ac tortor dignissim convallis aenean et tortor at. Netus et malesuada fames ac turpis egestas maecenas pharetra. Quis hendrerit dolor magna eget est lorem ipsum. Elementum nisi quis eleifend quam adipiscing vitae proin sagittis. Interdum varius sit amet mattis vulputate. Orci dapibus ultrices in iaculis nunc sed. Sagittis aliquam malesuada bibendum arcu. Vulputate dignissim suspendisse in est ante in nibh. Faucibus vitae aliquet nec ullamcorper sit. Auctor augue mauris augue neque gravida inQuam elementum pulvinar etiam non quam lacus suspendisse faucibus interdum. Velit ut tortor pretium viverra suspendisse potenti nullam ac tortor. Scelerisque felis imperdiet proin fermentum leo vel orci porta non. Lorem sed risus ultricies tristique nulla aliquet enim tortor at. Sed velit dignissim sodales ut eu sem integer vitae. Enim sit amet venenatis urna cursus eget nunc scelerisque viverra. Odio pellentesque diam volutpat commodo sed egestas. Ornare lectus sit amet est placerat in egestas. In ornare quam viverra orci sagittis eu volutpat odio facilisis. Orci dapibus ultrices in iaculis. Mauris sit amet massa vitae tortor condimentum lacinia quis vel. Egestas egestas fringilla phasellus faucibus scelerisque eleifend. Urna duis convallis convallis tellus id interdum velit laoreet. Urna molestie at elementum eu facilisis sed. Netus et malesuada fames ac turpis egestas. Pulvinar elementum integer enim neque volutpat. Fermentum et sollicitudin ac orci phasellus egestas tellus. Varius duis at consectetur lorem donec.</p>'
  },
  {
    title: 'Bagaimana cara membayar uang wajib bulanan ?',
    description:
      '<p><b>Uang wajib</b> perlu dibayar setiap bulannya. dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pretium lectus quam id leo in vitae. Sit amet luctus venenatis lectus magna fringilla urna. Nisi est sit amet facilisis magna. Convallis a cras semper auctor neque vitae tempus quam pellentesque. In arcu cursus euismod quis viverra nibh cras pulvinar mattis. Consectetur adipiscing elit ut aliquam. Nisl condimentum id venenatis a condimentum vitae sapien pellentesque habitant. Adipiscing elit duis tristique sollicitudin nibh sit amet commodo nulla. Ac tortor dignissim convallis aenean et tortor at. Netus et malesuada fames ac turpis egestas maecenas pharetra. Quis hendrerit dolor magna eget est lorem ipsum. Elementum nisi quis eleifend quam adipiscing vitae proin sagittis. Interdum varius sit amet mattis vulputate. Orci dapibus ultrices in iaculis nunc sed. Sagittis aliquam malesuada bibendum arcu. Vulputate dignissim suspendisse in est ante in nibh. Faucibus vitae aliquet nec ullamcorper sit. Auctor augue mauris augue neque gravida inQuam elementum pulvinar etiam non quam lacus suspendisse faucibus interdum. Velit ut tortor pretium viverra suspendisse potenti nullam ac tortor. Scelerisque felis imperdiet proin fermentum leo vel orci porta non. Lorem sed risus ultricies tristique nulla aliquet enim tortor at. Sed velit dignissim sodales ut eu sem integer vitae. Enim sit amet venenatis urna cursus eget nunc scelerisque viverra. Odio pellentesque diam volutpat commodo sed egestas. Ornare lectus sit amet est placerat in egestas. In ornare quam viverra orci sagittis eu volutpat odio facilisis. Orci dapibus ultrices in iaculis. Mauris sit amet massa vitae tortor condimentum lacinia quis vel. Egestas egestas fringilla phasellus faucibus scelerisque eleifend. Urna duis convallis convallis tellus id interdum velit laoreet. Urna molestie at elementum eu facilisis sed. Netus et malesuada fames ac turpis egestas. Pulvinar elementum integer enim neque volutpat. Fermentum et sollicitudin ac orci phasellus egestas tellus. Varius duis at consectetur lorem donec.</p>'
  }
];
