export const faqData = [
  {
    id: 'apa-itu-aplikasi-coopchick',
    title: 'Apa itu aplikasi CoopChick ?',
    role: ['ADMIN', 'MEMBER', 'CUSTOMER'],
    description:
      '<p><b>CoopChick</b> adalah sebuah aplikasi yang menerapkan prinsip keberjalanan koperasi secara digital pada domain peternakan ayam. Tujuan dari adanya aplikasi Coop Chick ini adalah untuk memudahkan para pelaku bisnis peternak ayam agar bisa bersatu sebagai satu koperasi lintas geografis dalam menopang kebutuhan bisnis peternakan ayam mulai dari penjualan produk peternak ayam hingga saling berbagi pengetahuan satu sama lain baik bagi para peternak ayam maupun bagi orang awam. Aplikasi Coop Chick terdiri atas lima modul yang saling berkaitan satu sama lain, yaitu modul penanganan keanggotaan, pencatatan aktivitas dan keaktifan anggota, pengelolaan keuangan anggota, <i>knowledge management</i>, dan modul transaksi jual beli (<i>e-commerce</i>).</p><img srcset="../../static/faq-images/CoopChickLogo.jpg" alt="CoopChick Logo" width="400" >'
  },
  {
    id: 'bagaimana-cara-melakukan-pembayaran-checkout-e-commerce',
    title: 'Bagaimana cara melakukan pembayaran checkout e-commerce ?',
    role: ['MEMBER', 'CUSTOMER'],
    description:
      '<p>Untuk melakukan <b>Checkout</b>, anda perlu dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pretium lectus quam id leo in vitae. Sit amet luctus venenatis lectus magna fringilla urna. Nisi est sit amet facilisis magna. Convallis a cras semper auctor neque vitae tempus quam pellentesque. In arcu cursus euismod quis viverra nibh cras pulvinar mattis. Consectetur adipiscing elit ut aliquam. Nisl condimentum id venenatis a condimentum vitae sapien pellentesque habitant. Adipiscing elit duis tristique sollicitudin nibh sit amet commodo nulla. Ac tortor dignissim convallis aenean et tortor at. Netus et malesuada fames ac turpis egestas maecenas pharetra. Quis hendrerit dolor magna eget est lorem ipsum. Elementum nisi quis eleifend quam adipiscing vitae proin sagittis. Interdum varius sit amet mattis vulputate. Orci dapibus ultrices in iaculis nunc sed. Sagittis aliquam malesuada bibendum arcu. Vulputate dignissim suspendisse in est ante in nibh. Faucibus vitae aliquet nec ullamcorper sit. Auctor augue mauris augue neque gravida inQuam elementum pulvinar etiam non quam lacus suspendisse faucibus interdum. Velit ut tortor pretium viverra suspendisse potenti nullam ac tortor. Scelerisque felis imperdiet proin fermentum leo vel orci porta non. Lorem sed risus ultricies tristique nulla aliquet enim tortor at. Sed velit dignissim sodales ut eu sem integer vitae. Enim sit amet venenatis urna cursus eget nunc scelerisque viverra. Odio pellentesque diam volutpat commodo sed egestas. Ornare lectus sit amet est placerat in egestas. In ornare quam viverra orci sagittis eu volutpat odio facilisis. Orci dapibus ultrices in iaculis. Mauris sit amet massa vitae tortor condimentum lacinia quis vel. Egestas egestas fringilla phasellus faucibus scelerisque eleifend. Urna duis convallis convallis tellus id interdum velit laoreet. Urna molestie at elementum eu facilisis sed. Netus et malesuada fames ac turpis egestas. Pulvinar elementum integer enim neque volutpat. Fermentum et sollicitudin ac orci phasellus egestas tellus. Varius duis at consectetur lorem donec.</p>'
  },
  {
    id: 'bagaimana-cara-membayar-simpanan-pokok-dan-wajib-bulanan',
    title: 'Bagaimana cara membayar simpanan pokok dan wajib bulanan ?',
    role: ['MEMBER'],
    description:
      '<ol type="1"><li>Pastikan <i>role</i> dari pengguna yang <i>login</i> adalah <i><b>member</b></i>.</li><li>Pergi ke halaman <b><i>dashboard</i></b> dan dapat melihat <b>status</b> dari simpanan pokok dan simpanan wajib pada periode saat ini. <img srcset="../../static/faq-images/CaraMembayarSimpanan2.jpg" alt="Cara membayar" width="400" ></li><li>Jika pada periode tersebut <b>belum lunas</b>, maka akan muncul <b>tombol bayar</b> di sebelah kanan kategori simpanan yang belum lunas tersebut. <img srcset="../../static/faq-images/CaraMembayarSimpanan3.jpg" alt="Cara membayar" width="400" ></li><li><b>Tekan tombol bayar</b> tersebut dan akan ditampilkan alternatif-alternatif <b>metode pembayaran</b> yang dapat dipakai, <b>tekan salah satu metode pembayaran</b> yang ingin digunakan. <img srcset="../../static/faq-images/CaraMembayarSimpanan4.jpg" alt="Cara membayar" width="400" ></li><li>Akan ditampilkan <b>nominal</b> yang harus dibayarkan pada transaksi tersebut, silahkan lanjut dengan mengisi <b>data dari akun pembayaran yang digunakan</b>, misalkan untuk pilihan <i>credit/debit card</i> diperlukan untuk mengisi <i>Card Number</i>, <i>Expiry Date</i>, dan <i>CVV</i>. <img srcset="../../static/faq-images/CaraMembayarSimpanan5.jpg" alt="Cara membayar" width="400" ></li><li>Setelah mengisikan data akun pembayaran dengan benar, lanjut dengan mengklik tombol <i><b>PAY NOW</b></i>. <img srcset="../../static/faq-images/CaraMembayarSimpanan6.jpg" alt="Cara membayar" width="400" ></li><li>Tunggu hingga keluar <b>status transaksi</b>, tekan tombol <b><i>DONE</i></b> atau tunggu hingga beberapa detik untuk setelah melakukan salah satunya akan diarahkan kembali ke halaman <b><i>dashboard</i></b>. <img srcset="../../static/faq-images/CaraMembayarSimpanan7.jpg" alt="Cara membayar" width="400" ></li><li>Lakukan pengecekan status simpanan sekarang, pastikan sudah terupdate (misalkan jika sudah terbayar maka status yang seharusnya ditampilkan lunas). <img srcset="../../static/faq-images/CaraMembayarSimpanan8.jpg" alt="Cara membayar" width="400" ></li><li>Selain itu, riwayat transaksi pembayaran simpanan ini juga akan ditampilkan pada halaman <i>report</i>. <img srcset="../../static/faq-images/CaraMembayarSimpanan9.jpg" alt="Cara membayar" width="400" ></li></ol>'
  },
  {
    id: 'apa-itu-saldo-dan-bagaimana-cara-kerjanya',
    title: 'Apa itu saldo dan bagaimana cara kerjanya?',
    role: ['ADMIN', 'MEMBER', 'CUSTOMER'],
    description:
      '<p>Saldo adalah dana yang diberikan kepada <i>member</i> atas hasil penjualan barangnya atau penerimaan sisa hasil usaha setiap awal periode. Saldo ini dapat dicairkan ke dalam saldo rekening bank pengguna yang didaftarkan. Hal yang perlu diperhatikan adalah saldo berbeda dengan jumlah saldo dari E-Money, seperti GoPay.</p><br><p>Bagaimana cara <b>mengecek saldo pengguna</b>?</p><ol type="1"><li>Pastikan <i>role</i> dari pengguna yang <i>login</i> adalah <i><b>member</b></i>.</li><li>Ada dua cara untuk mengecek saldo pengguna yaitu melalui <i>halaman <b>dashboard</i></b> atau melalui <b>halaman <i>seller center</i></b> jika member.</li><li>Halaman <i>dashboard</i> dapat diakses sebagai berikut</li><li>.<li>Halaman <i>seller center</i> dapat diakses sebagai berikut</li><li>.</li></ol><br><p>Bagaimana cara <b>melakukan pengajuan pencairan saldo</b>?</p><ol type="1"><li>Pastikan <i>role</i> dari pengguna yang <i>login</i> adalah <i><b>member</b></i>.</li><li></li><li></li></ol>'
  },
  {
    id: 'bagaimana-mekanisme-pembagian-shu-berdasarkan-keaktifan-anggota',
    title: 'Bagaimana mekanisme pembagian SHU berdasarkan keaktifan anggota?',
    role: ['ADMIN', 'MEMBER'],
    description:
      '<p>SHU adalah sisa hasil usaha yang akan dibayarkan kepada setiap <i>member</i> di awal periode. Pembayaran SHU ini akan langsung dimasukkan ke dalam saldo. </p>'
  },
  {
    id: 'bagaimana-cara-men-download-aplikasi',
    title: 'Bagaimana cara men-download aplikasi?',
    role: ['ADMIN', 'MEMBER', 'CUSTOMER'],
    description:
      '<p>lorem ipsun consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pretium lectus quam id leo in vitae. Sit amet luctus venenatis lectus magna fringilla urna. Nisi est sit amet facilisis magna. Convallis a cras semper auctor neque vitae tempus quam pellentesque. In arcu cursus euismod quis viverra nibh cras pulvinar mattis. Consectetur adipiscing elit ut aliquam. Nisl condimentum id venenatis a condimentum vitae sapien pellentesque habitant. Adipiscing elit duis tristique sollicitudin nibh sit amet commodo nulla. Ac tortor dignissim convallis aenean et tortor at. Netus et malesuada fames ac turpis egestas maecenas pharetra. Quis hendrerit dolor magna eget est lorem ipsum. Elementum nisi quis eleifend quam adipiscing vitae proin sagittis. Interdum varius sit amet mattis vulputate. Orci dapibus ultrices in iaculis nunc sed. Sagittis aliquam malesuada bibendum arcu. Vulputate dignissim suspendisse in est ante in nibh. Faucibus vitae aliquet nec ullamcorper sit. Auctor augue mauris augue neque gravida inQuam elementum pulvinar etiam non quam lacus suspendisse faucibus interdum. Velit ut tortor pretium viverra suspendisse potenti nullam ac tortor. Scelerisque felis imperdiet proin fermentum leo vel orci porta non. Lorem sed risus ultricies tristique nulla aliquet enim tortor at. Sed velit dignissim sodales ut eu sem integer vitae. Enim sit amet venenatis urna cursus eget nunc scelerisque viverra. Odio pellentesque diam volutpat commodo sed egestas. Ornare lectus sit amet est placerat in egestas. In ornare quam viverra orci sagittis eu volutpat odio facilisis. Orci dapibus ultrices in iaculis. Mauris sit amet massa vitae tortor condimentum lacinia quis vel. Egestas egestas fringilla phasellus faucibus scelerisque eleifend. Urna duis convallis convallis tellus id interdum velit laoreet. Urna molestie at elementum eu facilisis sed. Netus et malesuada fames ac turpis egestas. Pulvinar elementum integer enim neque volutpat. Fermentum et sollicitudin ac orci phasellus egestas tellus. Varius duis at consectetur lorem donec.</p>'
  }
];
