export const faqData = [
  {
    id: 'apa-itu-aplikasi-coopchick',
    title: 'Apa itu aplikasi CoopChick ?',
    role: ['ADMIN', 'MEMBER', 'CUSTOMER'],
    description:
      '<p><b>CoopChick</b> adalah sebuah aplikasi yang menerapkan prinsip keberjalanan koperasi secara digital pada domain peternakan ayam. Tujuan dari adanya aplikasi Coop Chick ini adalah untuk memudahkan para pelaku bisnis peternak ayam agar bisa bersatu sebagai satu koperasi lintas geografis dalam menopang kebutuhan bisnis peternakan ayam mulai dari penjualan produk peternak ayam hingga saling berbagi pengetahuan satu sama lain baik bagi para peternak ayam maupun bagi orang awam. Aplikasi Coop Chick terdiri atas lima modul yang saling berkaitan satu sama lain, yaitu modul penanganan keanggotaan, pencatatan aktivitas dan keaktifan anggota, pengelolaan keuangan anggota, <i>knowledge management</i>, dan modul transaksi jual beli (<i>e-commerce</i>).</p><img srcset="../../static/faq-images/CoopChickLogo.jpg" alt="CoopChick Logo" width="400" >'
  },
  {
    id: 'bagaimana-cara-melakukan-pembayaran-checkout-e-commerce',
    title: 'Bagaimana cara melakukan pembayaran checkout e-commerce ?',
    role: ['ADMIN', 'MEMBER', 'CUSTOMER'],
    description:
      '<p>Berikut ini adalah tata cara untuk melakukan pembelian di <b>E-Commerce</b>.<ol type="1"><li>Login terlebih dahulu ke dalam aplikasi.</li><li>Masuk ke dalam halaman e-commerce yang dapat diakses melalui navbar atau tombol produk yang terdapat pada halaman homepage.<img srcset="../../static/faq-images/checkout1.png" alt="checkout1" width="600" ></li><li>Pilih produk yang ingin dibeli. Anda dapat melakukan pencarian produk dengan menggunakan menu pencarian dan filter-filter yang telah tersedia. <img srcset="../../static/faq-images/checkout2.png" alt="checkout2" width="600" ></li><li>Tekan card dari salah satu produk yang tersedia pada hasil pencarian. </li><li>Tentukan banyaknya item dari produk yang ingin dibeli. Anda diberikan dua buah opsi, yaitu memasukkan barang ke dalam keranjang dengan tombol “Add to Cart” atau langsung melakukan checkout dengan menekan tombol “Buy Now”. <img srcset="../../static/faq-images/checkout3.png" alt="checkout3" width="600" ></li><li>Untuk memasuki halaman checkout, tekan tombol ikon “Cart” pada sisi kanan layar. <img srcset="../../static/faq-images/checkout4.png" alt="checkout5" width="200" ></li><li>Cek kembali seluruh produk yang telah dipesan. Apabila sudah cukup, tekan tombol Checkout. <img srcset="../../static/faq-images/checkout5.png" alt="checkout5" width="800" ></li><li>Pilih alamat pengiriman dari daftar alamat yang ada. Apabila ingin menambahkan alamat baru, tekan tombol “Add new address”.<img srcset="../../static/faq-images/checkout6.png" alt="checkout6" width="800" ></li><li>Pilih jenis pengiriman yang diinginkan. <img srcset="../../static/faq-images/checkout7.png" alt="checkout7" width="800" ></li><li>Pilih jenis pembayaran yang ingin dilakukan. <img srcset="../../static/faq-images/checkout8.png" alt="checkout8" width="800" ></li><li>Tekan tombol “Complete Order” apabila Anda sudah yakin dengan seluruh pilihan Anda.</li><li>Pilih jenis pengiriman yang diinginkan. <img srcset="../../static/faq-images/checkout9.png" alt="checkout9" width="800" ></li><li>Isilah field-field pada halaman pembayaran dengan memasukkan jenis pembayaran yang valid. <img srcset="../../static/faq-images/checkout10.png" alt="checkout10" width="800" ></li><li>Selamat! Anda telah berhasil melakukan pembelian di E-Commerce. <img srcset="../../static/faq-images/checkout11.png" alt="checkout11" width="800" ></li><li>Apabila terjadi kegagalan dalam pembayaran, Anda dapat mengunjungi halaman Riwayat Pesanan untuk melakukan pembayaran kembali. <img srcset="../../static/faq-images/checkout12.png" alt="checkout12" width="800" ></li></ol></p>'
  },
  {
    id: 'bagaimana-cara-mendaftarkan-gopay',
    title: 'Bagaimana cara mendaftarkan gopay ?',
    role: ['ADMIN', 'MEMBER', 'CUSTOMER'],
    description:
      '<p>Pengguna apapun <i>rolenya</i> dapat mendaftarkan Gopay untuk dapat melakukan transaksi pembayaran menggunakan Gopay tersebut. Cara mendaftarkan Gopay ke aplikasi Coopchick adalah sebagai berikut:<ol type="1"><li>Akses menu pengguna</li><li>Klik “Daftarkan Gopay”</li><li>Masukkan informasi Gopay pada <i>pop up window</i> yang muncul <img srcset="../../static/faq-images/gopay1.png" alt="gopay1" width="400" ></li><li>Pengguna akan diarahkan ke halaman <i>Third Party Payment Gateway</i> untuk memasukkan kode OTP yang telah dikirimkan ke nomor sesuai informasi yang telah diinput pada no (3)<img srcset="../../static/faq-images/gopay2.png" alt="gopay2" width="300" ></li><li>Pengguna akan diarahkan ke halaman <i>Third Party Payment Gateway</i> untuk memasukkan pin dari akun gopay <img srcset="../../static/faq-images/gopay3.png" alt="gopay3" width="300" ></li><li>Akses kembali menu pengguna dan akan tertera informasi saldo dari akun Gopay yang telah didaftarkan.</li><li>Klik “Batalkan Pendaftaran Gopay” untuk menghapus akun Gopay yang telah didaftarkan.<img srcset="../../static/faq-images/gopay4.png" alt="gopay4" width="300" ></ol></p>'
  },
  {
    id: 'bagaimana-cara-membayar-simpanan-pokok-dan-wajib-bulanan',
    title: 'Bagaimana cara membayar simpanan pokok dan wajib bulanan ?',
    role: ['ADMIN', 'MEMBER'],
    description:
      '<ol type="1"><li>Pastikan <i>role</i> dari pengguna yang <i>login</i> adalah <i><b>member</b></i>.</li><li>Pergi ke halaman <b><i>dashboard</i></b> dan dapat melihat <b>status</b> dari simpanan pokok dan simpanan wajib pada periode yang dapat dipilih (secara <i>default</i> periode saat ini). <img srcset="../../static/faq-images/simpanan1.png" alt="simpanan1" width="500" ></li><li>Jika pada periode tersebut <b>belum lunas</b>, maka akan muncul <b>tombol bayar</b> di bawah kategori simpanan yang belum lunas tersebut.</li><li>Pilih metode pembayaran yang ingin digunakan, pilih “Gopay Terdaftar” apabila pengguna sudah mendaftarkan Go Pay terlebih dahulu. Untuk memilih metode pembayaran lainnya yang dapat dipilih, pilih “Alternatif Lain”</li><li>Jika memilih “Gopay Terdaftar” maka akan diarahkan ke halaman untuk meminta PIN akun Gopay apabila nominal transaksi lebih dari Rp 100.000,00, atau transaksi akan langsung berjalan apabila transaksi kurang dari Rp 100.000,00.</li><li>Jika memilih “Alternatif Lain”, pilih salah satu <b>metode pembayaran</b> yang ingin digunakan. <img srcset="../../static/faq-images/simpanan2.png" alt="simpanan2" width="400" ></li><li>Akan ditampilkan <b>nominal</b> yang harus dibayarkan pada transaksi tersebut, silahkan lanjut dengan mengisi <b>data dari akun pembayaran yang digunakan</b>, misalkan untuk pilihan <i>credit/debit card</i> diperlukan untuk mengisi <i>Card Number, Expiry Date, dan CVV</i>.  <img srcset="../../static/faq-images/simpanan3.png" alt="simpanan3" width="400" ></li><li>Setelah mengisikan data akun pembayaran dengan benar, lanjut dengan mengklik tombol <i><b>PAY NOW</b></i><img srcset="../../static/faq-images/simpanan4.png" alt="simpanan4" width="400" ></li><li>Tunggu hingga keluar <b>status transaksi</b>, tekan tombol <b><i>DONE</i></b> atau tunggu hingga beberapa detik untuk setelah melakukan salah satunya akan diarahkan kembali ke halaman <b><i>dashboard</i></b>. <img srcset="../../static/faq-images/simpanan5.png" alt="simpanan5" width="400" ></li><li>Lakukan pengecekan status simpanan sekarang, pastikan sudah terupdate (misalkan jika sudah terbayar maka status yang seharusnya ditampilkan lunas). <img srcset="../../static/faq-images/simpanan6.png" alt="simpanan6" width="400" ></li><li>Selain itu, riwayat transaksi pembayaran simpanan ini juga akan ditampilkan pada halaman <i>report</i>. <img srcset="../../static/faq-images/simpanan7.png" alt="simpanan7" width="600" ></li></ol>'
  },
  {
    id: 'apa-itu-simpanan-sukarela',
    title: 'Apa itu simpanan sukarela?',
    role: ['ADMIN', 'MEMBER'],
    description:
      '<p>Simpanan sukarela adalah dana yang dapat ditambahkan oleh anggota dan dapat ditarik kembali dengan mekanisme pengajuan pencairan yang sama dengan pengajuan pencairan saldo. Informasi mengenai simpanan sukarela dapat diakses pada halaman dashboard. Untuk menambahkan simpanan sukarela dapat mengakses halaman Penambahan Simpanan Sukarela. <img srcset="../../static/faq-images/sukarela.png" alt="sukarela" width="300" ></p>'
  },
  {
    id: 'apa-itu-saldo-dan-bagaimana-cara-kerjanya',
    title: 'Apa itu saldo dan bagaimana cara kerjanya?',
    role: ['ADMIN', 'MEMBER'],
    description:
      '<p>Saldo adalah dana yang diberikan kepada <i>member</i> atas hasil penjualan barangnya atau penerimaan sisa hasil usaha setiap awal periode. Saldo ini dapat dicairkan ke dalam saldo rekening bank pengguna yang didaftarkan. Hal yang perlu diperhatikan adalah saldo berbeda dengan jumlah saldo dari E-Money, seperti GoPay.</p><br><p>Bagaimana cara <b>mengecek saldo pengguna</b>?</p><ol type="1"><li>Pastikan <i>role</i> dari pengguna yang <i>login</i> adalah <i><b>member</b></i>.</li><li>Ada dua cara untuk mengecek saldo pengguna yaitu melalui <i>halaman <b>dashboard</i></b> atau melalui <b>halaman <i>seller center</i></b> jika member.</li><li>Tampilan saldo pada halaman <i>dashboard</i> adalah sebagai berikut <img srcset="../../static/faq-images/saldo1.png" alt="saldo1" width="400" ></li><li>Tampilan saldo pada halaman <i>seller center</i> adalah sebagai berikut <img srcset="../../static/faq-images/saldo2.png" alt="saldo2" width="400" ></li></ol><br><p>Bagaimana cara <b>melakukan pengajuan pencarian saldo</b>?</p><ol type="1"><li>Pastikan <i>role</i> dari pengguna yang <i>login</i> adalah <i><b>member</b></i>.</li><li>Masuk ke halaman pengajuan pencairan dana yang dapat diakses dari halaman <i>dashboard</i> atau dari <i>sidebar</i> aplikasi.</li><li>Lakukan pendaftaran akun bank tujuan dana pencairan saldo akan dikirimkan. Jika telah mendaftarkan akun bank dapat mengubah informasi akun bank terdaftar. <img srcset="../../static/faq-images/saldo3.png" alt="saldo3" width="400" ></li><li>Masukkan jumlah saldo yang ingin dicairkan dan pilih tipe saldo sebagai tipe yang ingin dicairkan. <img srcset="../../static/faq-images/saldo4.png" alt="saldo4" width="400" ></li><li>Lihat daftar pengajuan pencairan saldo yang telah diajukan dan menunggu untuk dicairkan. <img srcset="../../static/faq-images/saldo5.png" alt="saldo5" width="600" ></li><br><p>Bagaimana cara <b>menyetujui pengajuan pencarian saldo</b>?</p><ol type="1"><li>Pastikan <i>role</i> dari pengguna yang <i>login</i> adalah <i><b>admin</b></i>.</li><li>Masuk ke halaman daftar pengajuan pencairan dana dimana akan ditampilkan daftar pengajuan pencairan dana yang telah diajukan oleh <i>member</i></li><li>Lakukan transfer sesuai data suatu pengajuan pencairan dana</li><li>Salin id pengajuan pencairan dana yang telah dipilih <img srcset="../../static/faq-images/saldo6.png" alt="saldo6" width="400" ></li><li>Masukkan id pengajuan pencairan dana beserta foto bukti transfer pengajuan pencairan dana tersebut ke halaman penyetujuan pencairan dana. <img srcset="../../static/faq-images/saldo7.png" alt="saldo7" width="400" ></li><li>Pastikan pengajuan pencairan dana tersebut sudah tidak muncul pada daftar pengajuan pencairan dana</i></ol>'
  },
  {
    id: 'bagaimana-mekanisme-pembagian-shu-berdasarkan-keaktifan-anggota',
    title: 'Bagaimana mekanisme pembagian SHU berdasarkan keaktifan anggota?',
    role: ['ADMIN', 'MEMBER'],
    description:
      '<p>SHU adalah sisa hasil usaha yang akan dibayarkan kepada setiap <i>member</i> di awal setiap tahun. Pembayaran SHU ini akan langsung dimasukkan ke dalam saldo. Riwayat penerimaan SHU dapat dilihat pada halaman <i>dashboard</i>. SHU ini akan ditambahkan secara otomatis ke saldo <i>member</i> oleh sistem. Nilai SHU yang didapat oleh seluruh <i>member</i> adalah sebesar 15% dari keuntungan koperasi dalam setahun. Nilai SHU ini akan dibagikan kepada setiap member bergantung pada keaktifan <i>member</i> tersebut dalam mengikuti rapat yang mengikutsertakan dirinya dan juga jumlah pembelian pada <i>E-Commerce</i> yang dilakukan olehnya dalam satu tahun tersebut.<img srcset="../../static/faq-images/shu.png" alt="shu" width="600" ></li></p>'
  },
  {
    id: 'bagaimana-cara-menjadi-anggota-koperasi',
    title: 'Bagaimana cara menjadi anggota koperasi?',
    role: ['ADMIN', 'CUSTOMER'],
    description:
      '<p>Request keanggotaan koperasi dapat dilakukan pada saat pendaftaran akun CoopChick. Untuk melakukan request menjadi anggota koperasi, saat registrasi pengguna perlu memilih “<b>Ya</b>” pada pertanyaan “<b>Apakah Anda ingin mendaftar sebagai Anggota Koperasi?</b>”<img srcset="../../static/faq-images/anggota1.png" alt="anggota1" width="600" >Bila pengguna telah melewatkan bagian ini saat pendaftaran akun, pengguna tetap dapat melakukan request menjadi anggota koperasi dengan memilih menu “<b>Request Anggota Koperasi</b>” pada profil pengguna. <img srcset="../../static/faq-images/anggota2.png" alt="anggota2" width="300" > Setelah melakukan request keanggotaan, silakan menunggu Admin untuk memverifikasi request keanggotaan Anda.</p>'
  },
  {
    id: 'bagaimana-cara-mengundurkan-diri-dari-keanggotaan-koperasi',
    title: 'Bagaimana cara mengundurkan diri dari keanggotaan koperasi?',
    role: ['ADMIN', 'MEMBER'],
    description:
      '<p>Untuk anggota koperasi, menu pengunduran diri dapat dipilih pada <i>sidebar</i> aplikasi. <img srcset="../../static/faq-images/mengundurkandiri1.png" alt="mengundurkandiri1" width="600" >Setelah memilih menu “<b>Pengunduran Diri</b>”, Anda dapat mengisi formulir pengunduran diri yang berisi alasan dan deskripsi alasan pengunduran diri. <img srcset="../../static/faq-images/mengundurkandiri2.png" alt="mengundurkandiri2" width="600" >Setelah menyetujui pengunduran diri, Anda dapat menunggu Admin untuk memverifikasi proses pengunduran keanggotaan Anda dari koperasi.</p>'
  }
];
