// ----------------------------------------------------------------------

export const role = [
  'Supplier DOC',
  'Peternak',
  'Supplier Pakan',
  'Supplier DOC',
  'Supplier DOC',
  'Pembeli',
  'Peternak',
  'Supplier Pakan',
  'Pembeli',
  'Pembeli',
  'Peternak',
  'Peternak',
  'Pembeli',
  'Supplier Pakan',
  'Peternak',
  'Pembeli',
  'Supplier Pakan',
  'Peternak',
  'Peternak',
  'Admin',
  'Supplier DOC',
  'Pembeli',
  'Pembeli',
  'Peternak',
  'Pembeli',
  'Pembeli',
  'Peternak',
  'Hr Manager',
  'Hr Manager',
  'Peternak',
  'Pembeli',
  'Peternak',
  'Pembeli',
  'Admin',
  'Pembeli',
  'Admin',
  'Pembeli',
  'Admin',
  'Pembeli',
  'Peternak'
];
